In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"cleaned_dataset.csv",parse_dates=["date"])

In [4]:
#Explonatory Data Analysis(EDA)
# finding mean,median and count
df[["unit_price","quantity","total_price"]].agg(["mean","median","count"]).round(2)

        unit_price  quantity  total_price
mean        356.41      2.95      1053.97
median      364.21      3.00       823.62
count      1200.00   1200.00      1200.00

In [5]:
#skewness check
#|skew| >1 means a skewed data
#normal skewness
df[["unit_price", "quantity", "total_price"]].skew()

unit_price    -0.026512
quantity       0.027922
total_price    0.891359
dtype: float64

In [6]:
#outlier detection
cols = ["unit_price", "quantity", "total_price"]

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"\n{col}: {len(outliers)} outliers")

unit_price: 0 outliers

quantity: 0 outliers

total_price: 8 outliers

In [7]:
#correlation analysis
cols = ["quantity","unit_price","total_price"]
corr =df[cols].corr()
print(corr.round(4))

             quantity  unit_price  total_price
quantity       1.0000      0.0146       0.6153
unit_price     0.0146      1.0000       0.7171
total_price    0.6153      0.7171       1.0000

In [15]:
#TRENDS AND PATTERNS
#Sales over time
df["month"]=df["date"].dt.to_period("M")
monthly_sales = df.groupby("month")["total_price"].sum().reset_index()
monthly_sales["month"] = monthly_sales["month"].astype(str)
monthly_sales.sort_values("total_price", ascending=False).reset_index(drop=True)

      month  total_price
0   2024-06     68068.54
1   2023-05     63836.84
2   2023-01     56685.75
3   2023-08     54352.14
4   2025-06     53047.40
5   2023-10     52607.85
6   2024-04     49613.14
7   2023-06     49500.19
8   2023-03     48609.37
9   2023-12     43754.73
10  2025-05     43396.64
11  2023-11     43079.67
12  2024-07     42963.98
13  2023-07     42820.66
14  2023-02     40117.66
15  2024-09     39794.98
16  2025-03     39200.66
17  2024-12     38785.77
18  2024-01     38528.08
19  2024-10     37226.97
20  2024-02     36909.57
21  2024-03     36030.90
22  2025-02     35317.55
23  2024-11     32413.76
24  2024-08     31991.07
25  2025-04     31821.20
26  2023-09     29526.67
27  2025-01     29099.40
28  2024-05     27909.11
29  2023-04     27751.71

In [19]:
#order volume over time
monthly_orders = df.groupby("month")["order_id"].count().reset_index()
monthly_orders.columns = ["month", "order_count"]
monthly_orders["month"] = monthly_orders["month"].astype(str)
monthly_orders.sort_values("order_count", ascending=False).reset_index(drop=True)

      month  order_count
0   2024-06           53
1   2023-08           51
2   2024-04           50
3   2025-03           49
4   2025-06           49
5   2023-05           49
6   2023-10           47
7   2023-01           47
8   2023-12           46
9   2023-06           45
10  2023-07           44
11  2024-09           44
12  2024-07           43
13  2023-03           43
14  2024-12           41
15  2023-11           41
16  2025-05           37
17  2025-02           37
18  2023-02           37
19  2024-03           36
20  2024-11           35
21  2024-05           34
22  2025-04           32
23  2024-02           32
24  2024-01           32
25  2023-04           31
26  2024-10           31
27  2023-09           29
28  2024-08           28
29  2025-01           27

In [21]:
#revenue by product
revenue_by_product = df.groupby("product")["total_price"].sum().reset_index()
revenue_by_product.columns = ["product", "total_revenue"]
revenue_by_product = revenue_by_product.sort_values("total_revenue", ascending=False).reset_index(drop=True)
revenue_by_product

   product  total_revenue
0    Chair      195620.11
1  Printer      195612.61
2   Laptop      192126.56
3   Tablet      186568.95
4  Monitor      175651.41
5     Desk      167459.93
6    Phone      151722.39

In [28]:
#order status pattern
status_analysis = df.groupby("order_status").agg(
    Order_Count=("order_id", "count"),
    Avg_TotalPrice=("total_price", "mean"),
    Total_Revenue=("total_price", "sum")
).reset_index()
status_analysis = status_analysis.sort_values("Order_Count", ascending=False).reset_index(drop=True)
status_analysis["Avg_TotalPrice"] = status_analysis["Avg_TotalPrice"].round(2)
status_analysis["Total_Revenue"]  = status_analysis["Total_Revenue"].round(2)
status_analysis

  order_status  Order_Count  Avg_TotalPrice  Total_Revenue
0    CANCELLED          250         1105.58      276396.21
1     RETURNED          247          984.93      243277.70
2      PENDING          237         1081.55      256328.15
3      SHIPPED          235         1047.49      246159.58
4    DELIVERED          231         1050.22      242600.32

In [31]:
#referral source performance
referral_analysis = df.groupby("referral_source").agg(
    Order_Count=("order_id", "count"),
    Avg_TotalPrice=("total_price", "mean"),
    Total_Revenue=("total_price", "sum")
).reset_index()
referral_analysis = referral_analysis.sort_values("Total_Revenue", ascending=False).reset_index(drop=True)
referral_analysis["Avg_TotalPrice"] = referral_analysis["Avg_TotalPrice"].round(2)
referral_analysis["Total_Revenue"]  = referral_analysis["Total_Revenue"].round(2)
referral_analysis

  referral_source  Order_Count  Avg_TotalPrice  Total_Revenue
0       Instagram          259         1062.88      275285.45
1           Email          250         1047.23      261808.55
2          Google          241         1039.18      250441.48
3        Facebook          228         1098.29      250410.90
4        Referral          222         1021.69      226815.58

In [33]:
#payment method vs order value
payment_analysis = df.groupby("payment_method").agg(
    Order_Count=("order_id", "count"),
    Avg_TotalPrice=("total_price", "mean"),
    Total_Revenue=("total_price", "sum")
).reset_index()

payment_analysis = payment_analysis.sort_values("Total_Revenue", ascending=False).reset_index(drop=True)
payment_analysis["Avg_TotalPrice"] = payment_analysis["Avg_TotalPrice"].round(2)
payment_analysis["Total_Revenue"]  = payment_analysis["Total_Revenue"]
payment_analysis

  payment_method  Order_Count  Avg_TotalPrice  Total_Revenue
0    CREDIT CARD          234         1127.55      263847.63
1         ONLINE          258         1017.22      262442.94
2           CASH          246         1056.04      259786.29
3      GIFT CARD          230         1070.97      246323.92
4     DEBIT CARD          232         1001.56      232361.18